---
# tasks file for postfix_relay
- name: Install apps
  ansible.builtin.package:
    name: postfix
    state: latest
    update_cache: true
- name: Remove default blank and old relay
  ansible.builtin.lineinfile:
    path: "/etc/postfix/main.cf"
    state: absent
    line: "{{ item }}"
  with_items:
    - "relayhost ="
    - 'relayhost = "{{ oldrelay }}"'
- name: Set relay
  ansible.builtin.lineinfile:
    path: "/etc/postfix/main.cf"
    state: present
    line: "{{ item }}"
  with_items:
    - 'relayhost = {{ relay }}'
  notify: Restart postfix
